package com.indicator_engine.indicator_system.Number;
import com.indicator_engine.model.indicator_system.Number.SelectNumberParameters
import com.indicator_engine.dao.GLACategoryDao
import com.indicator_engine.dao.GLAEntityDao
import com.indicator_engine.indicator_system.Number.ProcessUserFilters;
import java.util.List;

dialect  "mvel"

rule "When User does not opt for any Additional Filters"
when
    SelectNumberParameters ( userSpecifications.isEmpty() == true,
                             timeSpecifications.isEmpty() == true,
                             sessionSpecifications.isEmpty() == true,
                             entityValues.size()== 1,
                             entityValues.get(0).geteValues() ==  "ALL")
    $userParameter : SelectNumberParameters( $source : selectedSource,
                                             $platform : selectedPlatform,
                                             $action : selectedAction,
                                             $major : selectedMajor,
                                             $minor : selectedMinor,
                                             $type : selectedType,
                                             $key : entityValues)
then


   $userParameter.setHql("SELECT COUNT(*) FROM GLAEntity WHERE glaEvent.action ='"+$action+"'"
                             +" AND glaEvent.source = '"+ $source+"'"+ " AND glaEvent.platform = '"
                             + $platform+"'"+" AND glaEvent.glaCategory.major = '"+$major+"'"
                             +" AND glaEvent.glaCategory.minor = '"+$minor+"'"+" AND glaEvent.glaCategory.type = '"
                             +$type+"'"+" AND key = '"+ $key.get(0).getKey()+"'");

end

rule "When All Filters are Present"
when
    SelectNumberParameters ( userSpecifications.isEmpty() == false,
                                          timeSpecifications.isEmpty() == false,
                                          sessionSpecifications.isEmpty() == false,
                                          entityValues.isEmpty() == false )

    $pFilter : ProcessUserFilters()
    $userParameter : SelectNumberParameters( $source : selectedSource,
                                              $platform : selectedPlatform,
                                              $action : selectedAction,
                                              $major : selectedMajor,
                                              $minor : selectedMinor,
                                              $type : selectedType,
                                              $key : entityValues)

then

    $userParameter.setHql("SELECT COUNT(*) FROM GLAEntity WHERE glaEvent.action ='"+$action+"'"
                                 +" AND glaEvent.source = '"+ $source+"'"+ " AND glaEvent.platform = '"
                                 + $platform+"'"+" AND glaEvent.glaCategory.major = '"+$major+"'"
                                 +" AND glaEvent.glaCategory.minor = '"+$minor+"'"+" AND glaEvent.glaCategory.type = '"
                                 +$type+"'"+" AND key = '"+ $key.get(0).getKey()+"'");

    $pFilter.processEntities($key);


end


