/*
 * Open Learning Analytics Platform (OpenLAP) : Indicator Engine

 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
package com.indicator_engine.indicator_system.Number;
import com.indicator_engine.model.indicator_system.Number.EntitySpecification
import com.indicator_engine.indicator_system.Number.ProcessUserFilters;
import java.util.List;

dialect  "mvel"

rule "When no filter is Present"
when
    EntitySpecification ( userSpecifications.isEmpty() == true,
                             timeSpecifications.isEmpty() == true,
                             sessionSpecifications.isEmpty() == true,
                             entityValues.isEmpty() == true)
    $pFilter : ProcessUserFilters()
    $userParameter : EntitySpecification( $source : selectedSource,
                                             $platform : selectedPlatform,
                                             $action : selectedAction,
                                             $major : selectedMajor,
                                             $minor : selectedMinor,
                                             $type : selectedType,
                                             $key : entityValues,
                                             $pobject: persistenceObject,
                                             $filter : filteringType,
                                             $robject : retrievableObjects)
then

    $userParameter.setHql("SELECT " + $robject + " From ("
							+ "Select value, Entity_Key, Event_fk From Entity Where Event_fk in "
							+ "(SELECT E.Event_Id FROM Event E INNER JOIN Category C ON E.C_ID = C.C_Id "
							+ "WHERE C.Minor = '"+$minor+"' AND C.Major = '"+$major+"' AND C.Type = '"+$type+"' "
							+ "AND E.Action = '"+$action+"' AND E.Source IN "+$pFilter.processSource($source,$filter)
							+ " AND E.Platform = '"+$platform+"' ) ) d pivot ( max(value) "
							+ "for Entity_Key in (" + $robject + ") ) piv WHERE " + $pFilter.processNullValues($robject));

end

rule "When Only Entity Filtering (Default Rule) is Present"
when
    EntitySpecification ( userSpecifications.isEmpty() == true,
                             timeSpecifications.isEmpty() == true,
                             sessionSpecifications.isEmpty() == true,
                             entityValues.size()== 1,
                             entityValues.get(0).geteValues() ==  "ALL")
    $pFilter : ProcessUserFilters()
    $userParameter : EntitySpecification( $source : selectedSource,
                                             $platform : selectedPlatform,
                                             $action : selectedAction,
                                             $major : selectedMajor,
                                             $minor : selectedMinor,
                                             $type : selectedType,
                                             $key : entityValues,
                                             $pobject: persistenceObject,
                                             $filter : filteringType,
                                             $robject : retrievableObjects)
then

    $userParameter.setHql("SELECT " + $robject + " From ("
							+ "Select value, Entity_Key, Event_fk From Entity Where Event_fk in "
							+ "(SELECT E.Event_Id FROM Event E INNER JOIN Category C ON E.C_ID = C.C_Id "
							+ "WHERE C.Minor = '"+$minor+"' AND C.Major = '"+$major+"' AND C.Type = '"+$type+"' "
							+ "AND E.Action = '"+$action+"' AND E.Source IN "+$pFilter.processSource($source,$filter)
							+ " AND E.Platform = '"+$platform+"' ) ) d pivot ( max(value) "
							+ "for Entity_Key in (" + $robject + ") ) piv WHERE " + $pFilter.processNullValues($robject));

end

rule "When Only Entity Filtering (2+) is Present"
when
    EntitySpecification ( userSpecifications.isEmpty() == true,
                             timeSpecifications.isEmpty() == true,
                             sessionSpecifications.isEmpty() == true,
                             entityValues.isEmpty() == false)

    $pFilter : ProcessUserFilters()
    $userParameter : EntitySpecification( $source : selectedSource,
                                              $platform : selectedPlatform,
                                              $action : selectedAction,
                                              $major : selectedMajor,
                                              $minor : selectedMinor,
                                              $type : selectedType,
                                              $key : entityValues,
                                              $filter : filteringType,
                                              $pobject: persistenceObject,
                                              $robject : retrievableObjects)

then

	$userParameter.setHql("SELECT " + $robject + " From ("
							+ "Select value, Entity_Key, Event_fk From Entity Where Event_fk in "
							+ "(SELECT E.Event_Id FROM Event E INNER JOIN Category C ON E.C_ID = C.C_Id "
							+ "WHERE C.Minor = '"+$minor+"' AND C.Major = '"+$major+"' AND C.Type = '"+$type+"' "
							+ "AND E.Action = '"+$action+"' AND E.Source IN "+$pFilter.processSource($source,$filter)
							+ " AND E.Platform = '"+$platform+"' ) ) d pivot ( max(value) "
							+ "for Entity_Key in (" + $robject + ") ) piv "
							+ " Where " + $pFilter.processEntities($key,$filter) + " AND " + $pFilter.processNullValues($robject));
end

rule "When Only User Filtering and Entity Filtering are Present"
when
    EntitySpecification ( userSpecifications.isEmpty() == false,
                             timeSpecifications.isEmpty() == true,
                             sessionSpecifications.isEmpty() == true,
                             entityValues.isEmpty() == false)

    $pFilter : ProcessUserFilters()
    $userParameter : EntitySpecification( $source : selectedSource,
                                              $platform : selectedPlatform,
                                              $action : selectedAction,
                                              $major : selectedMajor,
                                              $minor : selectedMinor,
                                              $type : selectedType,
                                              $key : entityValues,
                                              $user : userSpecifications,
                                              $filter : filteringType,
                                              $pobject: persistenceObject,
                                              $robject : retrievableObjects)

then
								 
	$userParameter.setHql("SELECT " + $robject + " From ("
							+ "Select value, Entity_Key, Event_fk From Entity Where Event_fk in "
							+ "(SELECT E.Event_Id FROM Event E INNER JOIN Category C ON E.C_ID = C.C_Id "
							+ "WHERE C.Minor = '"+$minor+"' AND C.Major = '"+$major+"' AND C.Type = '"+$type+"' "
							+ "AND E.Action = '"+$action+"' AND E.Source IN "+$pFilter.processSource($source,$filter)
							+ " AND E.Platform = '"+$platform+"' "
							+ "AND E.U_Id In (Select U_Id FROM Users Where Name = '"+$pFilter.processUsers($user, $filter)
							+ "') ) ) d pivot ( max(value) for Entity_Key in (" + $robject + ") ) piv "
							+ " Where " + $pFilter.processEntities($key,$filter) + " AND " + $pFilter.processNullValues($robject));
end

rule "When Session & Entity Filtering are Present"
when
    EntitySpecification ( userSpecifications.isEmpty() == true,
                             timeSpecifications.isEmpty() == true,
                             sessionSpecifications.isEmpty() == false,
                             entityValues.isEmpty() == false)

    $pFilter : ProcessUserFilters()
    $userParameter : EntitySpecification( $source : selectedSource,
                                              $platform : selectedPlatform,
                                              $action : selectedAction,
                                              $major : selectedMajor,
                                              $minor : selectedMinor,
                                              $type : selectedType,
                                              $key : entityValues,
                                              $session : sessionSpecifications,
                                              $filter : filteringType,
                                              $pobject: persistenceObject,
                                              $robject : retrievableObjects)

then
	$userParameter.setHql("SELECT " + $robject + " From ("
							+ "Select value, Entity_Key, Event_fk From Entity Where Event_fk in "
							+ "(SELECT E.Event_Id FROM Event E INNER JOIN Category C ON E.C_ID = C.C_Id "
							+ "WHERE C.Minor = '"+$minor+"' AND C.Major = '"+$major+"' AND C.Type = '"+$type+"' "
							+ "AND E.Action = '"+$action+"' AND E.Source IN "+$pFilter.processSource($source,$filter)
							+ " AND E.Platform = '"+$platform+"' " + $pFilter.processSessions($session,$filter)
							+ " ) ) d pivot ( max(value) "
							+ "for Entity_Key in (" + $robject + ") ) piv "
							+ " Where " + $pFilter.processEntities($key,$filter) + " AND " + $pFilter.processNullValues($robject));
end


rule "When User Filtering, Session & Entity Filtering are Present"
when
    EntitySpecification ( userSpecifications.isEmpty() == false,
                             timeSpecifications.isEmpty() == true,
                             sessionSpecifications.isEmpty() == false,
                             entityValues.isEmpty() == false)

    $pFilter : ProcessUserFilters()
    $userParameter : EntitySpecification( $source : selectedSource,
                                              $platform : selectedPlatform,
                                              $action : selectedAction,
                                              $major : selectedMajor,
                                              $minor : selectedMinor,
                                              $type : selectedType,
                                              $key : entityValues,
                                              $user : userSpecifications,
                                              $session : sessionSpecifications,
                                              $filter : filteringType,
                                              $pobject: persistenceObject,
                                              $robject : retrievableObjects)

then
	$userParameter.setHql("SELECT " + $robject + " From ("
							+ "Select value, Entity_Key, Event_fk From Entity Where Event_fk in "
							+ "(SELECT E.Event_Id FROM Event E INNER JOIN Category C ON E.C_ID = C.C_Id "
							+ "WHERE C.Minor = '"+$minor+"' AND C.Major = '"+$major+"' AND C.Type = '"+$type+"' "
							+ "AND E.Action = '"+$action+"' AND E.Source IN "+$pFilter.processSource($source,$filter)
							+ " AND E.Platform = '"+$platform+"' "
							+ "AND E.U_Id In (Select U_Id FROM Users Where Name = '"+$pFilter.processUsers($user, $filter)
							+ "') " + $pFilter.processSessions($session,$filter)
							+ " ) ) d pivot ( max(value) for Entity_Key in (" + $robject + ") ) piv "
							+ " Where " + $pFilter.processEntities($key,$filter) + " AND " + $pFilter.processNullValues($robject));
end


rule "When Time & Entity Filtering are Present"
when
    EntitySpecification ( userSpecifications.isEmpty() == true,
                             timeSpecifications.isEmpty() == false,
                             sessionSpecifications.isEmpty() == true,
                             entityValues.isEmpty() == false)

    $pFilter : ProcessUserFilters()
    $userParameter : EntitySpecification( $source : selectedSource,
                                              $platform : selectedPlatform,
                                              $action : selectedAction,
                                              $major : selectedMajor,
                                              $minor : selectedMinor,
                                              $type : selectedType,
                                              $key : entityValues,
                                              $time : timeSpecifications,
                                              $filter : filteringType,
                                              $pobject: persistenceObject,
                                              $robject : retrievableObjects)

then
	$userParameter.setHql("SELECT " + $robject + " From ("
							+ "Select value, Entity_Key, Event_fk From Entity Where Event_fk in "
							+ "(SELECT E.Event_Id FROM Event E INNER JOIN Category C ON E.C_ID = C.C_Id "
							+ "WHERE C.Minor = '"+$minor+"' AND C.Major = '"+$major+"' AND C.Type = '"+$type+"' "
							+ "AND E.Action = '"+$action+"' AND E.Source IN "+$pFilter.processSource($source,$filter)
							+ " AND E.Platform = '"+$platform+"' " + $pFilter.processTime($time,$filter) 
							+ " ) ) d pivot ( max(value) "
							+ "for Entity_Key in (" + $robject + ") ) piv "
							+ " Where " + $pFilter.processEntities($key,$filter) + " AND " + $pFilter.processNullValues($robject));
end

rule "When All Filters are Present"
when
    EntitySpecification ( userSpecifications.isEmpty() == false,
                             timeSpecifications.isEmpty() == false,
                             sessionSpecifications.isEmpty() == false,
                             entityValues.isEmpty() == false)

    $pFilter : ProcessUserFilters()
    $userParameter : EntitySpecification( $source : selectedSource,
                                              $platform : selectedPlatform,
                                              $action : selectedAction,
                                              $major : selectedMajor,
                                              $minor : selectedMinor,
                                              $type : selectedType,
                                              $key : entityValues,
                                              $time : timeSpecifications,
                                              $filter : filteringType,
                                              $pobject: persistenceObject,
                                              $user : userSpecifications,
                                              $session : sessionSpecifications,
                                              $robject : retrievableObjects)

then
	$userParameter.setHql("SELECT " + $robject + " From ("
							+ "Select value, Entity_Key, Event_fk From Entity Where Event_fk in "
							+ "(SELECT E.Event_Id FROM Event E INNER JOIN Category C ON E.C_ID = C.C_Id "
							+ "WHERE C.Minor = '"+$minor+"' AND C.Major = '"+$major+"' AND C.Type = '"+$type+"' "
							+ "AND E.Action = '"+$action+"' AND E.Source IN "+$pFilter.processSource($source,$filter)
							+ " AND E.Platform = '"+$platform+"' " + $pFilter.processTime($time,$filter) 
							+ " AND E.U_Id In (Select U_Id FROM Users Where Name = '"+$pFilter.processUsers($user, $filter)
							+ "') " + $pFilter.processSessions($session,$filter)
							+ " ) ) d pivot ( max(value) "
							+ "for Entity_Key in (" + $robject + ") ) piv "
							+ " Where " + $pFilter.processEntities($key,$filter) + " AND " + $pFilter.processNullValues($robject));
end

rule "When Time, Entity and User Filters are present"
when
    EntitySpecification ( userSpecifications.isEmpty() == false,
                             timeSpecifications.isEmpty() == false,
                             sessionSpecifications.isEmpty() == true,
                             entityValues.isEmpty() == false)

    $pFilter : ProcessUserFilters()
    $userParameter : EntitySpecification( $source : selectedSource,
                                              $platform : selectedPlatform,
                                              $action : selectedAction,
                                              $major : selectedMajor,
                                              $minor : selectedMinor,
                                              $type : selectedType,
                                              $key : entityValues,
                                              $time : timeSpecifications,
                                              $filter : filteringType,
                                              $pobject: persistenceObject,
                                              $user : userSpecifications,
                                              $robject : retrievableObjects)

then
	$userParameter.setHql("SELECT " + $robject + " From ("
							+ "Select value, Entity_Key, Event_fk From Entity Where Event_fk in "
							+ "(SELECT E.Event_Id FROM Event E INNER JOIN Category C ON E.C_ID = C.C_Id "
							+ "WHERE C.Minor = '"+$minor+"' AND C.Major = '"+$major+"' AND C.Type = '"+$type+"' "
							+ "AND E.Action = '"+$action+"' AND E.Source IN "+$pFilter.processSource($source,$filter)
							+ " AND E.Platform = '"+$platform+"' " + $pFilter.processTime($time,$filter) 
							+ " AND E.U_Id In (Select U_Id FROM Users Where Name = '"+$pFilter.processUsers($user, $filter)
							+ "') ) ) d pivot ( max(value) "
							+ "for Entity_Key in (" + $robject + ") ) piv "
							+ " Where " + $pFilter.processEntities($key,$filter) + " AND " + $pFilter.processNullValues($robject));
end

rule "When Time, Entity & Session Filters are present"
when
    EntitySpecification ( userSpecifications.isEmpty() == true,
                             timeSpecifications.isEmpty() == false,
                             sessionSpecifications.isEmpty() == false,
                             entityValues.isEmpty() == false)

    $pFilter : ProcessUserFilters()
    $userParameter : EntitySpecification( $source : selectedSource,
                                              $platform : selectedPlatform,
                                              $action : selectedAction,
                                              $major : selectedMajor,
                                              $minor : selectedMinor,
                                              $type : selectedType,
                                              $key : entityValues,
                                              $time : timeSpecifications,
                                              $filter : filteringType,
                                              $pobject: persistenceObject,
                                              $session : sessionSpecifications,
                                              $robject : retrievableObjects)

then
	$userParameter.setHql("SELECT " + $robject + " From ("
							+ "Select value, Entity_Key, Event_fk From Entity Where Event_fk in "
							+ "(SELECT E.Event_Id FROM Event E INNER JOIN Category C ON E.C_ID = C.C_Id "
							+ "WHERE C.Minor = '"+$minor+"' AND C.Major = '"+$major+"' AND C.Type = '"+$type+"' "
							+ "AND E.Action = '"+$action+"' AND E.Source IN "+$pFilter.processSource($source,$filter)
							+ " AND E.Platform = '"+$platform+"' " + $pFilter.processTime($time,$filter) 
							+ " " + $pFilter.processSessions($session,$filter)
							+ " ) ) d pivot ( max(value) "
							+ "for Entity_Key in (" + $robject + ") ) piv "
							+ " Where " + $pFilter.processEntities($key,$filter) + " AND " + $pFilter.processNullValues($robject));
end