package com.indicator_engine.indicator_system.Number;
import com.indicator_engine.model.indicator_system.Number.SelectNumberParameters
import com.indicator_engine.indicator_system.Number.ProcessUserFilters;
import java.util.List;

dialect  "mvel"

rule "When Only Entity Filtering (Default Rule) is Present"
when
    SelectNumberParameters ( userSpecifications.isEmpty() == true,
                             timeSpecifications.isEmpty() == true,
                             sessionSpecifications.isEmpty() == true,
                             entityValues.size()== 1,
                             entityValues.get(0).geteValues() ==  "ALL")
    $userParameter : SelectNumberParameters( $source : selectedSource,
                                             $platform : selectedPlatform,
                                             $action : selectedAction,
                                             $major : selectedMajor,
                                             $minor : selectedMinor,
                                             $type : selectedType,
                                             $key : entityValues)
then


   $userParameter.setHql("SELECT COUNT(*) FROM GLAEntity WHERE glaEvent.action ='"+$action+"'"
                             +" AND glaEvent.source = '"+ $source+"'"+ " AND glaEvent.platform = '"
                             + $platform+"'"+" AND glaEvent.glaCategory.major = '"+$major+"'"
                             +" AND glaEvent.glaCategory.minor = '"+$minor+"'"+" AND glaEvent.glaCategory.type = '"
                             +$type+"'"+" AND key = '"+ $key.get(0).getKey()+"'");
end

rule "When Only Entity Filtering (more than 2) is Present"
when
    SelectNumberParameters ( userSpecifications.isEmpty() == true,
                             timeSpecifications.isEmpty() == true,
                             sessionSpecifications.isEmpty() == true,
                             entityValues.isEmpty() == false,
                             entityValues.size() >= 1  )

    $pFilter : ProcessUserFilters()
    $userParameter : SelectNumberParameters( $source : selectedSource,
                                              $platform : selectedPlatform,
                                              $action : selectedAction,
                                              $major : selectedMajor,
                                              $minor : selectedMinor,
                                              $type : selectedType,
                                              $key : entityValues,
                                              $filter : selectedFilteringType)

then

    $userParameter.setHql("SELECT COUNT(*) FROM GLAEntity WHERE glaEvent.action ='"+$action+"'"
                                 +" AND glaEvent.source = '"+ $source+"'"+ " AND glaEvent.platform = '"
                                 + $platform+"'"+" AND glaEvent.glaCategory.major = '"+$major+"'"
                                 +" AND glaEvent.glaCategory.minor = '"+$minor+"'"+" AND glaEvent.glaCategory.type = '"
                                 +$type+"'"+ " AND key IN " + $pFilter.processEntities($key,$filter));
end

rule "When Only User Filtering is Present"
when
    SelectNumberParameters ( userSpecifications.isEmpty() == false,
                             timeSpecifications.isEmpty() == true,
                             sessionSpecifications.isEmpty() == true,
                             entityValues.isEmpty() == true)

    $pFilter : ProcessUserFilters()
    $userParameter : SelectNumberParameters( $source : selectedSource,
                                              $platform : selectedPlatform,
                                              $action : selectedAction,
                                              $major : selectedMajor,
                                              $minor : selectedMinor,
                                              $type : selectedType,
                                              $user : userSpecifications,
                                              $filter : selectedFilteringType)

then
    $userParameter.setHql("SELECT COUNT(*) FROM GLAEntity WHERE glaEvent.action ='"+$action+"'"
                                 +" AND glaEvent.source = '"+ $source+"'"+ " AND glaEvent.platform = '"
                                 + $platform+"'"+" AND glaEvent.glaCategory.major = '"+$major+"'"
                                 +" AND glaEvent.glaCategory.minor = '"+$minor+"'"+" AND glaEvent.glaCategory.type = '"
                                 +$type+"'"+ " AND"   + $pFilter.processUsers($user,$filter));
end

